### ISSUE TITLE
took pictures hv \ some could use a "continue in the next page" message. also one code was out so took picture of that too

### ISSUE THREAD

**Issue by iTzMajor** [silent-mobius/Python_ORA#1]
![23](https://user-images.githubusercontent.com/54765909/74027586-2a8acd00-49b1-11ea-9db3-6845963d08ae.PNG)
![24](https://user-images.githubusercontent.com/54765909/74027590-2b236380-49b1-11ea-8af2-fb020cecad0f.PNG)
![25](https://user-images.githubusercontent.com/54765909/74027592-2bbbfa00-49b1-11ea-8428-76cb88a9722d.PNG)
![26](https://user-images.githubusercontent.com/54765909/74027593-2bbbfa00-49b1-11ea-8987-750e5c1fe008.PNG)
![1](https://user-images.githubusercontent.com/54765909/74027594-2c549080-49b1-11ea-8f79-f6a98151983f.PNG)
![2](https://user-images.githubusercontent.com/54765909/74027595-2c549080-49b1-11ea-91e7-6a2245fbc8f8.PNG)
![3](https://user-images.githubusercontent.com/54765909/74027596-2c549080-49b1-11ea-8c6f-9fc9fa487272.PNG)
![4](https://user-images.githubusercontent.com/54765909/74027599-2ced2700-49b1-11ea-9339-b3ffb645b39b.PNG)
![5](https://user-images.githubusercontent.com/54765909/74027600-2ced2700-49b1-11ea-9302-f1c44651b856.PNG)
![6](https://user-images.githubusercontent.com/54765909/74027601-2d85bd80-49b1-11ea-8745-e6975a90fd49.PNG)
![7](https://user-images.githubusercontent.com/54765909/74027602-2d85bd80-49b1-11ea-9d2e-41d85240e2bd.PNG)
![8](https://user-images.githubusercontent.com/54765909/74027603-2e1e5400-49b1-11ea-89c1-851aa31c488d.PNG)
![9](https://user-images.githubusercontent.com/54765909/74027604-2e1e5400-49b1-11ea-9b2b-26a86c329622.PNG)
![10](https://user-images.githubusercontent.com/54765909/74027605-2eb6ea80-49b1-11ea-80e6-641a7a3d337d.PNG)
![11](https://user-images.githubusercontent.com/54765909/74027609-2eb6ea80-49b1-11ea-88e4-390faaece8db.PNG)
![12](https://user-images.githubusercontent.com/54765909/74027610-2eb6ea80-49b1-11ea-92c1-6a69648afff0.PNG)
![13](https://user-images.githubusercontent.com/54765909/74027613-2f4f8100-49b1-11ea-9e20-bc19626ba47a.PNG)
![14](https://user-images.githubusercontent.com/54765909/74027616-2f4f8100-49b1-11ea-87db-ee8635e083cb.PNG)
![15](https://user-images.githubusercontent.com/54765909/74027617-2fe81780-49b1-11ea-8f62-066576c0019f.PNG)
![16](https://user-images.githubusercontent.com/54765909/74027619-2fe81780-49b1-11ea-904e-6a5e5a5e189b.PNG)
![17](https://user-images.githubusercontent.com/54765909/74027621-2fe81780-49b1-11ea-9ce7-67b204b2268d.PNG)
![18](https://user-images.githubusercontent.com/54765909/74027624-3080ae00-49b1-11ea-9477-181a523f90cc.PNG)
![19](https://user-images.githubusercontent.com/54765909/74027626-3080ae00-49b1-11ea-8988-b807a92283aa.PNG)
![20](https://user-images.githubusercontent.com/54765909/74027628-31194480-49b1-11ea-9586-746cc3354dba.PNG)
![21](https://user-images.githubusercontent.com/54765909/74027630-31194480-49b1-11ea-92cd-2072408b77bd.PNG)
too
![22](https://user-images.githubusercontent.com/54765909/74027631-31b1db00-49b1-11ea-9ca9-b965bdfbc1c8.PNG)

**Comment by silent-mobius** [comment]
Not implicable. Pdf is generated from markdown, there is no control where pages starts and ends. Try reading via github.
