### ISSUE TITLE
Spelling/Grammar Correction, Missing/Uncorrect Information And Own Opinion.

### ISSUE THREAD

**Issue by yebk** [silent-mobius/Python_ORA#4]
### Spelling/Grammar correction:
1. At the start of the book **[Python 101]** you forgot to add dots to finish a sentence. You need to spell "what is a program", and not what's a program.
2. At **["Higher level" languages]** incorrect Spelling "...infor..." change to "...info...".
3. At **[Types of languages]** incorrect start dots.
4. At **[Procedural Languages]** add a space at "programming,based".
5. At **[REPL: Python Interpreter]-[LINE 9]** "...and parses it into a data structure in memory." Change it to "...and parses it into a data structure in the memory." (i added "the memory").
6. At **[REPL: Python Interpreter]-[LINE 11]** "In Lisp, evaluating an s-expression...". I think You have to change it to "a s-expression...", not "an s-expression...".
7. At **[Saving the code]-[LINE 3]** change "...saved in to the file..." to "...saved into the file...".
8. At **[ATOM (Image)]** Change "...bunch tools..." to "...bunch of tools...".
9. At **[Python Indentation]** Here "Python uses indentation to indicate a block of code." Change that dot at the end of the sentence into Colon (":").
10. At **[Python Variables]** You wrote the same sentence 2 time ("Python has no command for declaring a variable").
11. At **[Python Data Types]-[Python Numbers]** what is this "`<! -- print(type(z)) -->`"?

### Missing/Uncorrect Information:
1. At **[Python Data Types]-[Built-in Data Types]** I would add the **`long`** and **`double`** Data-Types that were at Python 2.X for history lesson.
2. At **[Python Data Types]-[Built-in Data Types]** There is no **`memoryview`** Data-Type at the categories.
3. At **[Python Data Types]-[Python Numbers]** You are missing the **`complex`** Data-Type (you wrote "There are three numeric types in Python:" and show only two.).
4. At **[Python Data Types]-[Python Numbers]** You don't show an example of the **`complex`** Data-Type.
5. At **[Python Strings]-[How to access characters in a string?]**. At the end there is a text: "...elements as shown below.". I think You meant You write above.

### Own opinion and other:
1. At **[Python Syntax]** There is that "...[img]" at line 1 and 2, I think You wanted to put an image there or is it just me?
2. At **[Python Data Types]-[Python Numbers]** There is images of examples, and You don't show the result of the code. I think You need to show the results.
3. At **[Python Data Types]-[Python Numbers]-[Float]** In My opinion the examples You gave are not enough understandable for beginners:
`convert from int to float: a = float(x)`
`convert from float to int: b = int(y)`.
I would add the output of the code.

### Note:
Where I wrote "At **[......]**", this is the Title/Line of the place I found/think there's an issue. I did that so you can find the issue by using the **`CRTL+F`** shortcut to find text.
I stoped checking At **[Python Data Types]-[How to change or delete a string?]**
**02.07.2020 - 03:27PM**

**Comment by silent-mobius** [comment]
Hi  yebk,
I would prefer to have individual issue on individual error/proble,
